language: python
python:
  - "3.9.1"

# virtualenv:
# system_site_packages: true
addons:
  firefox:
    latest

before install:
  # - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  # - tar -xzf geckodriver-v0.20.1-linux64.tar.gz
  - sudo cp geckodriver /usr/bin

install:
  - pip install -r requirements.txt

env:
  DJANGO_SETTINGS_MODULE="papounet_diet.settings.production"

services:
  - postgresql

script:
  - ./manage.py test

branches:
  only:
    - integration
