dist: bionic
language: python

python:
  - "3.9.1"

addons:
  firefox:
    latest
  apt:
    packages:
      firefox-geckodriver

install:
  - pip install -r requirements.txt
  
env:
  DJANGO_SETTINGS_MODULE="papounet_diet.settings.production"

services:
  - postgresql

script:
  - ./manage.py test 

branches:
  only:
    - integration
