dist: bionic
language: python

python:
  - "3.9.1"

addons:
  firefox:
    latest

install:
  - pip install tchappui-webdrivers

before-script:
  - install-webdrivers --path /usr/local/bin/

env:
  DJANGO_SETTINGS_MODULE="papounet_diet.settings.production"

services:
  - postgresql

script:
  - ./manage.py test

branches:
  only:
    - integration
