dist: bionic
language: python

python:
  - "3.9.1"

addons:
  firefox:
    latest

install:
  - pip install -r requirements.txt
  - wget -N https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz -P ~/

  - tar -xzf ~/geckodriver-v0.28.0-linux64.tar.gz -C ~/
  - rm ~/geckodriver-v0.28.0-linux64.tar.gz
  - sudo mv -f ~/geckodriver /usr/local/share
  - sudo chmod +x /usr/local/share/geckodriver
  - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver

env:
  DJANGO_SETTINGS_MODULE="papounet_diet.settings.production"

services:
  - postgresql

script:
  - ./manage.py test 

branches:
  only:
    - integration
